### ISSUE TITLE
Fade in animation and hover (colour change)

### ISSUE THREAD

**Issue by Dev040302** [Dev040302/-Flippy-WEb-App#1]
add a fade in animation to the heading and list items and background color when hovered
--**update the main.html file** 
-- Here's an example for your refere
![hover](https://github.com/Dev040302/-Flippy-WEb-App/assets/78677597/79db771f-98fa-4620-bf09-3b791b692336)
nce

**Comment by singhalgarvit** [comment]
where are the list items
